webserver:
  build: images/webserver
  ports:
    - "80:80"
  links:
    - mysql:mysql
    - neo4j:neo4j
  volumes_from:
    - apidata
    - frontenddata
  environment:
    NEO4J_URL: http://neo4j:neo5j@neo4j:7474

apidata:
  image: busybox
  volumes:
    - "/var/www/api/app/cache"
    - "/var/www/api/app/logs"
    - "./sites/api/api.conf:/etc/nginx/sites-enabled/api.conf"
    - "./www/api/:/var/www/api/"

frontenddata:
  image: busybox
  volumes:
    - "./sites/frontend/frontend.conf:/etc/nginx/sites-enabled/frontend.conf"
    - "./www/frontend/:/var/www/frontend/"

mysql:
  image: tutum/mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_PASS: password
    ON_CREATE_DB: "apidb"

neo4j:
  image: neo4j:3.0
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - "./neo4j/data:/data"
  environment:
    NEO4J_AUTH: "neo4j/neo5j"

